teams:
  url: "https://teams.live.com/meet/9361118592033?p=aYlqt4GMv5KZmgkJGh"
  captions_file: "output/captions_{timestamp}.txt"
  fetch_interval: 1
  xpath:
    list: ".//div[@data-tid='closed-caption-v2-virtual-list-content']"
    author: ".//span[@data-tid='author']"
    text: ".//span[@data-tid='closed-caption-text']"

openai:
  url: "https://chat.openai.com/"
  config["openai"]["translated_file"]: "output/captions_zh_{timestamp}.txt"
  translation_interval: 5

driver:
  edge:
    executable_path: "drivers/edge/msedgedriver.exe"
